logging:
  level:
    org:
      springframework: INFO
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: NONE
  main:
    banner-mode: 'off'
  sql:
    init:
      data-locations: classpath*:db/postgresql/data.sql
      mode: always
      schema-locations: classpath*:db/postgresql/schema.sql
  thymeleaf:
    mode: HTML
